language: java
# use Java 8
jdk:
- openjdk8

sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
branches:
    only:
    - master
before_install:
  - chmod +x mvnw
deploy:
    provider: cloudfoundry
    api: $CF_API
    username: $CF_USER
    password: $CF_PASS
    organization: $CF_ORG
    space: $CF_ENV
